version: '3'
services:

  #PHP Service
  app:
    build: .
    container_name: shop
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: shop
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./configurations/conf/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - shop-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./configurations/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - shop-network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: shop_db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: beetroot
      MYSQL_DATABASE: beetroot
      MYSQL_USER: beetroot
      MYSQL_PASSWORD: beetroot
    volumes:
      - ./shop_db:/var/lib/mysql
      - ./configurations/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - shop-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8008:80"
    environment:
      PMA_HOST: shop_db
      PMA_PORT: 3306
    networks:
      - shop-network

#Volumes
volumes:
  dbdata:
    driver: "local"
#Docker Networks
networks:
  shop-network:
    driver: bridge
