version: "3.9"

services:
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beetroot
      MYSQL_USER: beetroot
      MYSQL_PASSWORD: beetroot
    restart: always
    container_name: mysql_beetroot

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8008:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306

volumes:
  mysqldata:
    driver: "local"